### ISSUE TITLE
Dinput8 error

### ISSUE THREAD

**Issue by Gnbiggs** [SkyProc/translation#2]
Does the Dinput8 file work for Windows Home? It seems to crash for some users who are running Windows home?

**Comment by Andoryuuta** [comment]
Hello.

This project has been discontinued since 2023-06-15. To my knowledge, some entirely unaffiliated groups have modified my original DLL to work with newer versions of the game client. I'm completely uninvolved in that effort.

Any dinput8.dll that is being shared/distributed currently is not mine, and I have no idea what it does/doesn't support or what modification have been made to it.
